version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started
      - mvn install
      - cp target/tracker-server.jar $CODEBUILD_SRC_DIR_SourceArtifact
  post_build:
    commands:
      - echo Build completed
artifacts:
  base-directory: $CODEBUILD_SRC_DIR_SourceArtifact
  files:
    - '**/*'
