name: Java CI with Gradle

on:
  push:
    branches: [ fleetmap ]
  pull_request:
    branches: [ fleetmap ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Set db pass
      run: sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' traccar.xml

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: traccar-tf
        environment_name: Traccar-env
        version_label: ${{ github.run_number }}
        region: us-east-1
        deployment_package: deploy.zip
